### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by zangrjol** [zangrjol/Optimizacija-donosnosti-portfelja#1]
dej kej nared vasko

**Comment by sejpravim** [comment]
ajde no vasko

**Comment by Vasily1** [comment]
pa ce ne sledis. ne morem ti pomagat...

**Comment by Vasily1** [comment]
prosim, ce nadaljujete z delom.

**Comment by zangrjol** [comment]
čis nč še nisi naredu

**Comment by zangrjol** [comment]
sam sosedo hočš bengat

**Comment by Vasily1** [comment]
vidim, da to znamo uporabljati. Bravo!
